version: '3'
services:
  app:
    container_name: kencinema
    restart: always
    env_file: .env
    stdin_open: true
    tty: true
    environment:
      - NODE_ENV=$NODE_ENV
    build: .:/usr/src/index
    ports:
      - '9456:4000'
    networks: 
      - kencinema
  db:
    container_name: app_db
    image: "postgres:11.5-alpine"
    volumes:
      - ./pg-init-scripts:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_MULTIPLE_DATABASES=app,app_test
    networks: 
      - kencinema
volumes: 
  my_dbdata:
networks: 
  kencinema:
    driver: bridge
